src = ["app"]

select = [
  "F", # Enable pyflakes rules.
  "I", # Enable isort rules.
  ]
ignore = []

exclude = [
    ".git",
    "third_party",
    "venv",
]

# Assume Python 3.9
target-version = "py39"

[isort]
force-single-line = true
force-to-top = ["log"]
