src = ["app"]

select = [
  # Enable select pydocstyle rules.
  "D202", # No blank lines allowed after function docstring
  "D205", # 1 blank line required between summary line and description
  "D212", # Multi-line docstring summary should start at the first line
  "D415", # First line should end with a period, question mark, or exclamation point
  "F", # Enable pyflakes rules.
  "I", # Enable isort rules.
  ]
ignore = []

exclude = [
    ".git",
    "third_party",
    "venv",
]

# Assume Python 3.9
target-version = "py39"

[isort]
force-single-line = true
force-to-top = ["log"]

[pydocstyle]
convention = "google"
