#!/bin/bash

# Exit build script on first failure.
set -e

# Echo commands to stdout.
set -x

# Exit on unset variable.
set -u

# Location of app source files.
SOURCE_DIR=app

# Location of virtualenv.
VIRTUALENV_DIR=venv

# Delete pyc files from previous builds.
find . \
  -name "*.pyc" \
  -type f \
  -not -path "./${VIRTUALENV_DIR}/*" \
  -delete

# Run unit tests and calculate code coverage.
coverage run \
  --source "$SOURCE_DIR" \
  -m unittest discover
coverage report

# Check that source has correct formatting.
yapf \
  --diff \
  --recursive \
  --style google \
  ./ \
  --exclude=third_party/* \
  --exclude=venv/*

# Check correct sorting for imports.
isort \
  --recursive \
  --force-single-line-imports \
  --diff \
  --check-only \
  --skip-glob=third_party/* \
  --skip-glob=venv/*

# Run static analysis for Python bugs/cruft.
pyflakes "${SOURCE_DIR}/"
