---
- name: create TinyPilot privileged folder
  file:
    path: "{{ tinypilot_privileged_dir }}"
    state: directory
    owner: "root"
    group: "root"

- name: copy usb-gadget initializer
  copy:
    src: init-usb-gadget
    dest: "{{ tinypilot_privileged_dir }}/init-usb-gadget"
    owner: root
    group: root
    mode: "0700"

- name: copy usb-gadget de-initializer
  copy:
    src: remove-usb-gadget
    dest: "{{ tinypilot_privileged_dir }}/remove-usb-gadget"
    owner: root
    group: root
    mode: "0700"

- name: install usb-gadget initializer as a service
  copy:
    src: usb-gadget.service
    dest: /lib/systemd/system/usb-gadget.service
    owner: root
    group: root
    mode: "0644"
  register: usb_gadget_file

- name: enable systemd usb-gadget initializer service file
  systemd:
    name: usb-gadget
    enabled: yes
    daemon_reload: "{{ usb_gadget_file.changed }}"
