---
- name: detect OS
  set_fact:
    tinypilot_is_os_raspbian: "{{ ansible_lsb.id is defined and ansible_lsb.id == 'Raspbian' }}"
    tinypilot_is_os_debian: "{{ ansible_lsb.id is defined and ansible_lsb.id == 'Debian' }}"

- name: choose the default version of uStreamer to install
  set_fact:
    ustreamer_repo_version: "{{ ustreamer_repo_version_modern }}"

- name: override the target version of uStreamer with a legacy version for compatibility
  set_fact:
    ustreamer_repo_version: "{{ ustreamer_repo_version_legacy }}"
  when: (tinypilot_is_os_raspbian or tinypilot_is_os_debian) and
    ((ansible_distribution_major_version | int) <= 10)

- name: import uStreamer role
  import_role:
    name: ansible-role-ustreamer
