---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: debian11
    image: geerlingguy/docker-debian11-ansible
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - "${PWD}/debian-pkgs:/opt/debian-pkgs:ro"
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  log: true
  inventory:
    hosts:
      all:
        vars:
          ansible_user: root
          tinypilot_debian_package_path: /opt/debian-pkgs/${TINYPILOT_DEBIAN_PACKAGE}
verifier:
  name: ansible
scenario:
  name: default
  test_sequence:
    - lint
    - destroy
    - syntax
    - create
    - converge
    - idempotence
    - destroy
