from hid.keycodes import azerty
from hid.keycodes import qwerty

# TODO: Choose layout based on settings.
_LAYOUT = azerty


class Error(Exception):
    pass


class UnrecognizedKeyCodeError(Error):
    pass


# JS keycodes source: https://github.com/wesbos/keycodes

# TODO: For simplicity, we map all modifiers keys to the left key, but we could
# support distinct keys for left and right if we check the location parameter
# from the JavaScript message.
_JS_TO_HID_KEYCODES = {
    3: _LAYOUT.KEYCODE_PAUSE_BREAK,
    8: _LAYOUT.KEYCODE_BACKSPACE_DELETE,
    9: _LAYOUT.KEYCODE_TAB,
    12: _LAYOUT.KEYCODE_CLEAR,
    13: _LAYOUT.KEYCODE_ENTER,
    16: _LAYOUT.KEYCODE_LEFT_SHIFT,
    17: _LAYOUT.KEYCODE_LEFT_CTRL,
    18: _LAYOUT.KEYCODE_LEFT_ALT,
    19: _LAYOUT.KEYCODE_PAUSE_BREAK,
    20: _LAYOUT.KEYCODE_CAPS_LOCK,
    21: _LAYOUT.KEYCODE_HANGEUL,
    25: _LAYOUT.KEYCODE_HANJA,
    27: _LAYOUT.KEYCODE_ESCAPE,
    32: _LAYOUT.KEYCODE_SPACEBAR,
    33: _LAYOUT.KEYCODE_PAGE_UP,
    34: _LAYOUT.KEYCODE_PAGE_DOWN,
    35: _LAYOUT.KEYCODE_END,
    36: _LAYOUT.KEYCODE_HOME,
    37: _LAYOUT.KEYCODE_LEFT_ARROW,
    38: _LAYOUT.KEYCODE_UP_ARROW,
    39: _LAYOUT.KEYCODE_RIGHT_ARROW,
    40: _LAYOUT.KEYCODE_DOWN_ARROW,
    41: _LAYOUT.KEYCODE_SELECT,
    43: _LAYOUT.KEYCODE_EXECUTE,
    44: _LAYOUT.KEYCODE_PRINT_SCREEN,
    45: _LAYOUT.KEYCODE_INSERT,
    46: _LAYOUT.KEYCODE_DELETE,
    47: _LAYOUT.KEYCODE_HELP,
    48: _LAYOUT.KEYCODE_NUMBER_0,
    49: _LAYOUT.KEYCODE_NUMBER_1,
    50: _LAYOUT.KEYCODE_NUMBER_2,
    51: _LAYOUT.KEYCODE_NUMBER_3,
    52: _LAYOUT.KEYCODE_NUMBER_4,
    53: _LAYOUT.KEYCODE_NUMBER_5,
    54: _LAYOUT.KEYCODE_NUMBER_6,
    55: _LAYOUT.KEYCODE_NUMBER_7,
    56: _LAYOUT.KEYCODE_NUMBER_8,
    57: _LAYOUT.KEYCODE_NUMBER_9,
    58: _LAYOUT.KEYCODE_COLON,
    59: _LAYOUT.KEYCODE_SEMICOLON,
    60: _LAYOUT.KEYCODE_LESS_THAN,
    61: _LAYOUT.KEYCODE_EQUAL_SIGN,
    65: _LAYOUT.KEYCODE_A,
    66: _LAYOUT.KEYCODE_B,
    67: _LAYOUT.KEYCODE_C,
    68: _LAYOUT.KEYCODE_D,
    69: _LAYOUT.KEYCODE_E,
    70: _LAYOUT.KEYCODE_F,
    71: _LAYOUT.KEYCODE_G,
    72: _LAYOUT.KEYCODE_H,
    73: _LAYOUT.KEYCODE_I,
    74: _LAYOUT.KEYCODE_J,
    75: _LAYOUT.KEYCODE_K,
    76: _LAYOUT.KEYCODE_L,
    77: _LAYOUT.KEYCODE_M,
    78: _LAYOUT.KEYCODE_N,
    79: _LAYOUT.KEYCODE_O,
    80: _LAYOUT.KEYCODE_P,
    81: _LAYOUT.KEYCODE_Q,
    82: _LAYOUT.KEYCODE_R,
    83: _LAYOUT.KEYCODE_S,
    84: _LAYOUT.KEYCODE_T,
    85: _LAYOUT.KEYCODE_U,
    86: _LAYOUT.KEYCODE_V,
    87: _LAYOUT.KEYCODE_W,
    88: _LAYOUT.KEYCODE_X,
    89: _LAYOUT.KEYCODE_Y,
    90: _LAYOUT.KEYCODE_Z,
    91: _LAYOUT.KEYCODE_LEFT_META,
    93: _LAYOUT.KEYCODE_CONTEXT_MENU,
    94: _LAYOUT.KEYCODE_NUMPAD_4,  # / (UK)
    96: _LAYOUT.KEYCODE_NUMPAD_0,
    97: _LAYOUT.KEYCODE_NUMPAD_1,
    98: _LAYOUT.KEYCODE_NUMPAD_2,
    99: _LAYOUT.KEYCODE_NUMPAD_3,
    100: _LAYOUT.KEYCODE_NUMPAD_4,
    101: _LAYOUT.KEYCODE_NUMPAD_5,
    102: _LAYOUT.KEYCODE_NUMPAD_6,
    103: _LAYOUT.KEYCODE_NUMPAD_7,
    104: _LAYOUT.KEYCODE_NUMPAD_8,
    105: _LAYOUT.KEYCODE_NUMPAD_9,
    106: _LAYOUT.KEYCODE_NUMPAD_MULTIPLY,
    107: _LAYOUT.KEYCODE_NUMPAD_PLUS,
    109: _LAYOUT.KEYCODE_NUMPAD_MINUS,
    110: _LAYOUT.KEYCODE_NUMPAD_DOT,
    111: _LAYOUT.KEYCODE_NUMPAD_DIVIDE,
    112: _LAYOUT.KEYCODE_F1,
    113: _LAYOUT.KEYCODE_F2,
    114: _LAYOUT.KEYCODE_F3,
    115: _LAYOUT.KEYCODE_F4,
    116: _LAYOUT.KEYCODE_F5,
    117: _LAYOUT.KEYCODE_F6,
    118: _LAYOUT.KEYCODE_F7,
    119: _LAYOUT.KEYCODE_F8,
    120: _LAYOUT.KEYCODE_F9,
    121: _LAYOUT.KEYCODE_F10,
    122: _LAYOUT.KEYCODE_F11,
    123: _LAYOUT.KEYCODE_F12,
    124: _LAYOUT.KEYCODE_F13,
    125: _LAYOUT.KEYCODE_F14,
    126: _LAYOUT.KEYCODE_F15,
    127: _LAYOUT.KEYCODE_F16,
    128: _LAYOUT.KEYCODE_F17,
    129: _LAYOUT.KEYCODE_F18,
    130: _LAYOUT.KEYCODE_F19,
    131: _LAYOUT.KEYCODE_F20,
    132: _LAYOUT.KEYCODE_F21,
    133: _LAYOUT.KEYCODE_F22,
    134: _LAYOUT.KEYCODE_F23,
    144: _LAYOUT.KEYCODE_NUM_LOCK,
    145: _LAYOUT.KEYCODE_SCROLL_LOCK,
    161: _LAYOUT.KEYCODE_NUMBER_1,
    163: _LAYOUT.KEYCODE_HASH,
    164: _LAYOUT.KEYCODE_DOLLAR_SIGN,
    165: _LAYOUT.KEYCODE_U_ACCENT,
    169: _LAYOUT.KEYCODE_RIGHT_PARENTHESIS,
    173: _LAYOUT.KEYCODE_MINUS,
    179: _LAYOUT.KEYCODE_MEDIA_PLAY_PAUSE,
    168: _LAYOUT.KEYCODE_REFRESH,
    186: _LAYOUT.KEYCODE_SEMICOLON,
    187: _LAYOUT.KEYCODE_EQUAL_SIGN,
    188: _LAYOUT.KEYCODE_COMMA,
    189: _LAYOUT.KEYCODE_MINUS,
    190: _LAYOUT.KEYCODE_PERIOD,
    191: _LAYOUT.KEYCODE_FORWARD_SLASH,
    192: _LAYOUT.KEYCODE_ACCENT_GRAVE,
    219: _LAYOUT.KEYCODE_LEFT_BRACKET,
    220: _LAYOUT.KEYCODE_BACKSLASH,
    221: _LAYOUT.KEYCODE_RIGHT_BRACKET,
    222: _LAYOUT.KEYCODE_SINGLE_QUOTE,
    223: _LAYOUT.KEYCODE_ACCENT_GRAVE,
    225: _LAYOUT.KEYCODE_RIGHT_ALT,
}


def convert(keystroke):
    control_chars = 0
    for i, pressed in enumerate([
            keystroke.ctrl_modifier, keystroke.shift_modifier,
            keystroke.alt_modifier, keystroke.meta_modifier
    ]):
        if pressed:
            control_chars |= 1 << i
    try:
        return control_chars, _JS_TO_HID_KEYCODES[keystroke.key_code]
    except KeyError:
        raise UnrecognizedKeyCodeError('Unrecognized key code %s (%d)' %
                                       (keystroke.key, keystroke.key_code))
