#!/bin/bash
# shellcheck disable=SC2034
#
# Markers used to denote autogenerated changes to config files..

readonly MARKER_START='# --- AUTOGENERATED BY TINYPILOT - START ---'
readonly MARKER_END='# --- AUTOGENERATED BY TINYPILOT - END ---'
