#!/bin/bash
#
# Immediately apply the current static IP config to the device.

# Exit on first failure.
set -e

# Echo commands before executing them, by default to stderr.
set -x

# Exit on unset variable.
set -u

# Check which OS is running.
OS_CODENAME="$(grep '^VERSION_CODENAME' /etc/os-release | cut --delimiter '=' --fields 2)"

# Ignore hangup signals to avoid exiting the shell when the network interface
# is flushed and a new IP is assigned. This was an issue when running the script
# manually via a remote shell.
trap '' HUP
if [[ "${OS_CODENAME}" == "bullseye" ]]; then
  ip address flush dev eth0
  systemctl restart \
    dhcpcd.service
else
  nmcli connection down 'Wired connection 1'
  nmcli connection up 'Wired connection 1'
fi
