#!/bin/bash
#
# Change the hostname of the machine.

# Exit on unset variable.
set -u

# Exit on first error.
set -e

readonly VALID_HOSTNAME_PATTERN='^[-0-9A-Za-z]+$'

print_help() {
  cat << EOF
Usage: ${0##*/} [-h] new_hostname
Change the hostname of this machine.
  -h Display this help and exit.
EOF
}

# Parse command-line arguments.
while getopts 'h' opt; do
  case "${opt}" in
    h)
      print_help
      exit
      ;;
    *)
      print_help >&2
      exit 1
  esac
done

# Ensure 'new_hostname' is given.
shift $((OPTIND - 1))
if (( $# == 0 )); then
  echo 'Input parameter missing: new_hostname' >&2
  exit 1
fi

# Validate 'new_hostname' parameter.
# See here for the rules:
# https://man7.org/linux/man-pages/man7/hostname.7.html
readonly NEW_HOSTNAME="$1"
if ! [[ "${NEW_HOSTNAME}" =~ $VALID_HOSTNAME_PATTERN ]] \
  || [[ "${NEW_HOSTNAME}" == -* ]] \
  || [[ "${NEW_HOSTNAME}" == 'localhost' ]] \
  || (( ${#NEW_HOSTNAME} > 63 )) \
  ; then
  echo 'Invalid hostname' >&2
  exit 1
fi

# We use `hostnamectl set-hostname xyz` instead of `hostnamectl hostname xyz`
# because `set-hostname` is backwards compatible with the Bullseye version of
# `hostnamectl`. `hostnamectl hostname xyz` is only supported on the Bookworm
# version.
hostnamectl set-hostname "${NEW_HOSTNAME}"
