#!/bin/bash
#
# Writes the main Janus config file, rendered from the config template file.

# Exit on unset variable.
set -u

# Exit on first error.
set -e

pushd /opt/tinypilot
. venv/bin/activate && \
  PYTHONPATH=/opt/tinypilot/app \
    ./scripts/render-template \
  < /usr/share/tinypilot/templates/janus.jcfg.j2 \
  > /etc/janus/janus.jcfg && \
  deactivate
popd
