#!/bin/bash
#
# Enable TinyPilot WiFi access point.

set -eux

if (( "${EUID}" != 0 )); then
  >&2 echo 'This script requires root privileges.'
  >&2 echo 'Please re-run with sudo:' >&2
  >&2 echo "  sudo $0 $*" >&2
  >&2 exit 1
fi

print_help() {
  cat <<EOF
Usage: ${0##*/} [--help] [--password NETWORK_PASSWORD]
Enable TinyPilot WiFi access point.
  --help                      Display this help and exit.
  --password NETWORK_PASSWORD The network password. If not specified, you will
                              be prompted for a password.
EOF
}

# Parse command-line arguments.

NETWORK_PASSWORD=''
while (( "$#" > 0 )); do
  case "$1" in
    --help)
      print_help
      exit
      ;;
    --password)
      if (( "$#" < 2 )); then
        shift;
        break;
      fi
      NETWORK_PASSWORD="$2"
      shift # For flag name.
      shift # For flag value.
      ;;
    *)
      >&2 echo "Unknown agrument: $1"
      >&2 print_help
      exit 1
      ;;
  esac
done

# Validate command-line arguments.

if [[ -z "${NETWORK_PASSWORD}" ]]; then
  read -s -p 'Set a WiFi password: ' NETWORK_PASSWORD
fi
readonly NETWORK_PASSWORD

# Choose the name for the Wi-Fi network that TinyPilot will create.
NETWORK_NAME="TinyPilotWiFi"

# Choose IP addresses and ranges to use.
WIFI_AP_IP_ADDRESS='192.168.50.1'
WIFI_AP_CLIENT_IP_RANGE_START='192.168.50.2'
WIFI_AP_CLIENT_IP_RANGE_END='192.168.50.100'

# Enter your country code: https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2
WIFI_COUNTRY="US"

apt install hostapd dnsmasq --yes && \
  sed --in-place '/interface wlan0/d' /etc/dhcpcd.conf && \
  sed --in-place "/ip_address=${WIFI_AP_IP_ADDRESS}/d" /etc/dhcpcd.conf && \
  sed --in-place '/nohook wpa_supplicant/d' /etc/dhcpcd.conf

. /opt/tinypilot-privileged/scripts/lib/markers.sh
cat << EOF | tee --append /etc/dhcpcd.conf
${MARKER_START}
interface wlan0
static ip_address=${WIFI_AP_IP_ADDRESS}/24
nohook wpa_supplicant
${MARKER_END}
EOF

cat << EOF | tee /etc/hostapd/hostapd.conf
country_code=${WIFI_COUNTRY}
interface=wlan0
ssid=${NETWORK_NAME}
hw_mode=g
channel=7
macaddr_acl=0
auth_algs=1
ignore_broadcast_ssid=0
wpa=2
wpa_passphrase=${NETWORK_PASSWORD}
wpa_key_mgmt=WPA-PSK
wpa_pairwise=TKIP
rsn_pairwise=CCMP
EOF

cat << EOF | tee /etc/dnsmasq.conf
interface=wlan0
dhcp-range=${WIFI_AP_CLIENT_IP_RANGE_START},${WIFI_AP_CLIENT_IP_RANGE_END},255.255.255.0,24h
domain=wlan
address=/gw.wlan/${WIFI_AP_IP_ADDRESS}
EOF

cp --no-clobber /etc/wpa_supplicant/wpa_supplicant.conf \
  /etc/wpa_supplicant/wpa_supplicant.conf.bak

if ! rfkill list wlan | grep -q "yes"; then
  touch /etc/wpa_supplicant/wlan_enabled
fi

cat << EOF | tee /etc/wpa_supplicant/wpa_supplicant.conf
ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
update_config=1
EOF

rfkill unblock wlan && \
  systemctl unmask hostapd dnsmasq && \
  systemctl enable hostapd dnsmasq && \
  systemctl restart hostapd dnsmasq
