#!/bin/bash
#
# Reverts any changes made by the set-static-ip script.

# Exit on first error.
set -e

print_help() {
  cat << EOF
Usage: ${0##*/} [--quiet] [--no-apply] [--help]

Reverts any changes made by the set-static-ip script.
  --quiet:          Suppress the confirmation message.
  --no-apply:       Make changes without applying them to the system.
  --help:           Display this help text.
EOF
}

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
readonly SCRIPT_DIR
readonly CONFIG_FILE="/etc/dhcpcd.conf"
# shellcheck source=lib/markers.sh
. "${SCRIPT_DIR}/lib/markers.sh"

# Parse command-line arguments.
if ! NEW_ARGS=$(getopt -q -o "" -l "quiet,no-apply,help,interface:" -- "$@"); then
  print_help
  exit 1
fi

# Process command-line arguments.
eval set -- "${NEW_ARGS}"
while true; do
  case "$1" in
    --quiet)
      readonly QUIET="true"
      shift 1
      ;;
    --interface)
      # See https://github.com/tiny-pilot/tinypilot/issues/1710#issuecomment-1885680744.
      echo 'The --interface flag is no longer supported' >&2
      exit 1
      ;;
    --help)
      print_help
      exit
      ;;
    --no-apply)
      readonly APPLY_CHANGES="false"
      shift 1
      ;;
    --)
      shift
      break
      ;;
  esac
done

# Default to not quiet.
if [[ -z "${QUIET}" ]] ; then
  readonly QUIET="false"
fi

# Default to applying changes.
if [[ -z "${APPLY_CHANGES}" ]] ; then
  readonly APPLY_CHANGES="true"
fi

# Exit on unset variable
set -u

# Remove any existing auto-generated configuration as populated by the
# set-static-ip script.
dhcpcd_original=()
is_in_marker_section='false'
while IFS= read -r line; do
  if "${is_in_marker_section}" && [[ "${line}" == "${MARKER_END}" ]]; then
    is_in_marker_section='false'
    continue
  fi
  if "${is_in_marker_section}" || [[ "${line}" == "${MARKER_START}" ]]; then
    is_in_marker_section='true'
    continue
  fi
  dhcpcd_original+=("${line}")
done < "${CONFIG_FILE}"

if "${is_in_marker_section}"; then
  echo 'Unclosed marker section' >&2
  exit 1
fi

# Convert array of lines to a single string.
OLD_CONFIG_FILE=$(printf "%s\n" "${dhcpcd_original[@]}")
readonly OLD_CONFIG_FILE

# Write original file contents back to the file.
echo "${OLD_CONFIG_FILE}" | sudo tee "${CONFIG_FILE}" > /dev/null

if [[ "${APPLY_CHANGES}" == "true" ]] ; then
  "${SCRIPT_DIR}/apply-static-ip"
fi

if [[ "${QUIET}" == "false" ]] ; then
  echo "Any changes made by the set-static-ip script have been reverted."
fi
