#!/bin/bash
#
# Reverts any changes made by the set-static-ip script.

# Exit on first error.
set -e

print_help() {
  cat << EOF
Usage: ${0##*/} [--quiet] [--help]

Reverts any changes made by the set-static-ip script.
  --quiet:          Suppress the confirmation message.
  --help:           Display this help text.
EOF
}

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
readonly SCRIPT_DIR
# shellcheck source=lib/markers.sh
. "${SCRIPT_DIR}/lib/markers.sh"

# Parse command-line arguments.
if ! NEW_ARGS=$(getopt -q -o "" -l "quiet,help,interface:" -- "$@"); then
  print_help
  exit 1
fi

# Process command-line arguments.
eval set -- "${NEW_ARGS}"
while true; do
  case "$1" in
    --quiet)
      readonly QUIET="true"
      shift 1
      ;;
    --interface)
      # See https://github.com/tiny-pilot/tinypilot/issues/1710#issuecomment-1885680744.
      echo 'The --interface flag is no longer supported' >&2
      exit 1
      ;;
    --help)
      print_help
      exit
      ;;
    --)
      shift
      break
      ;;
  esac
done

# Default to not quiet.
if [[ -z "${QUIET}" ]] ; then
  readonly QUIET="false"
fi

# Exit on unset variable
set -u

# Check which OS is running.
OS_CODENAME="$(grep '^VERSION_CODENAME' /etc/os-release | cut --delimiter '=' --fields 2)"

if [[ "${OS_CODENAME}" == "bullseye" ]]; then
  # Remove any existing marker sections from the config file.
  "${SCRIPT_DIR}/strip-marker-sections" /etc/dhcpcd.conf
else
  # Bookworm process.
  # we need the interface here - just assume physical interface for now?
  nmcli connection modify 'Wired connection 1' \
    ipv4.method auto \
    ipv4.addresses '' \
    ipv4.gateway '' \
    ipv4.dns ''
fi

# Apply changes.
"${SCRIPT_DIR}/apply-static-ip"

if [[ "${QUIET}" == "false" ]] ; then
  echo "Any changes made by the set-static-ip script have been reverted."
fi
