#!/bin/bash

# Triggers an update of the system.

# Echo commands before executing them, by default to stderr.
set -x

# Treat undefined environment variables as errors.
set -u

# Exit on first error.
set -e

# Hand over to latest `get-tinypilot.sh` script.
# The URL is trusted.
# nosemgrep: curl-pipe-bash
curl \
  --silent \
  --show-error \
  https://raw.githubusercontent.com/tiny-pilot/tinypilot/master/get-tinypilot.sh | \
    bash -
