#!/bin/bash

# Print commands to terminal (stderr).
set -x

# Treat undefined environment variables as errors.
set -u

# Exit on first error.
set -e

curl \
  --silent \
  --show-error \
  https://raw.githubusercontent.com/tiny-pilot/tinypilot/master/get-tinypilot.sh | \
    bash -
