#!/bin/bash

# Creates a TinyPilot installation bundle from the bundle/ folder.
# Fetches all required dependencies automatically.

# Exit on first error.
set -e

# Exit on unset variable.
set -u

# Echo commands to stdout.
set -x

# TODO (jotaen): parameterize script to make the installation work for
#                TinyPilot Pro as well.

# TODO: Adjust the workflow so that we build Debian packages as part of the same
# workflow on the same system that we build the bundle so that we don't have to
# retrieve the Debian package file from a remote URL.
readonly PKG_URL_TINYPILOT='https://packages.tinypilotkvm.com/community/tinypilot-1.7.1-1-armhf.deb'
readonly REPO_ANSIBLE_TINYPILOT='https://github.com/tiny-pilot/ansible-role-tinypilot.git'
readonly REPO_ANSIBLE_NGINX='https://github.com/tiny-pilot/ansible-role-nginx'
readonly REPO_ANSIBLE_USTREAMER='https://github.com/tiny-pilot/ansible-role-ustreamer'

readonly BUNDLE_DIR='bundle'
readonly OUTPUT_DIR='dist'

pushd "${BUNDLE_DIR}"

wget "${PKG_URL_TINYPILOT}"

# Copy each Ansible role dependency into the bundle and add a version file.
for GIT_URL in $REPO_ANSIBLE_TINYPILOT $REPO_ANSIBLE_NGINX $REPO_ANSIBLE_USTREAMER
do
  git clone \
    --depth 1 \
    --branch master \
    "${GIT_URL}"
  FOLDER_NAME="$(echo "${GIT_URL}" | sed 's|https://github.com/tiny-pilot/||' | sed 's|.git||')"
  pushd "${FOLDER_NAME}"
  git rev-parse --short HEAD > VERSION
  popd
done

# Remove all `.git/` folders.
find . \
  -type d \
  -name .git \
  -prune \
  -exec rm -rf {} \;

# Prepare a Python virtual environment for running Ansible.
python3 -m venv venv
# shellcheck disable=SC1091 # Don’t follow sourced script.
. venv/bin/activate
pip install pip==21.3.1
pip install -r requirements.txt

popd

# Generate build output.
mkdir -p "${OUTPUT_DIR}"
ls -lahR "${BUNDLE_DIR}" > "${OUTPUT_DIR}/files.txt"
tar \
  --create \
  --file "${OUTPUT_DIR}/tinypilot.tar" \
  --directory "${BUNDLE_DIR}" \
  .
