#!/bin/bash
#
# Download and install the Backblaze CLI tool for a Linux based system.

# Exit script on first failure.
set -e

# Echo commands before executing them, by default to stderr.
set -x

# Exit on unset variable.
set -u

readonly VERSION='3.4.0'
wget \
  "https://github.com/Backblaze/B2_Command_Line_Tool/releases/download/v${VERSION}/b2-linux" \
  --output-document b2
chmod +x ./b2
b2 version
