#!/bin/bash
#
# Verify the integrity of the TinyPilot installation bundle.

# Exit script on first failure.
set -e

# Echo commands before executing them, by default to stderr.
set -x

# Exit on unset variable.
set -u

BUNDLE_FILE="$(ls dist/tinypilot*.tgz)"
readonly BUNDLE_FILE
BUNDLE_DIR="$(mktemp --tmpdir=/var/tmp --directory)"
readonly BUNDLE_DIR

# Check bundle size.
BUNDLE_SIZE_BYTES="$(wc -c <"${BUNDLE_FILE}")"
if [[ "${BUNDLE_SIZE_BYTES}" -eq 0 ]]; then
  >&2 echo 'Bundle size is zero.'
  exit 1
fi
if [[ "${BUNDLE_SIZE_BYTES}" -gt 5000000 ]]; then
  >&2 echo 'Bundle size is larger than 5mb.'
  exit 1
fi

# Extract tarball to temporary directory.
tar \
  --gunzip \
  --extract \
  --file "${BUNDLE_FILE}" \
  --directory "${BUNDLE_DIR}"
pushd "${BUNDLE_DIR}"

# Check extracted bundle directory size.
BUNDLE_DIR_SIZE_BYTES="$(du --summarize --bytes "${BUNDLE_DIR}" | cut --fields 1)"
readonly BUNDLE_DIR_SIZE_BYTES
if [[ "${BUNDLE_DIR_SIZE_BYTES}" -gt 500000000 ]]; then
  >&2 echo "Bundle directory size is larger than 500mb, which exceeds the size of the installer's RAMdisk"
  exit 1
fi

# Check that install script exists.
if [[ ! -f install ]]; then
  >&2 echo 'Bundle is missing install script.'
  exit 1
fi

# List Debian package contents.
dpkg --contents tinypilot*.deb

# Check that Ansible roles exist.
readonly ANSIBLE_ROLES=(
  ansible-role-nginx
  ansible-role-tinypilot
  ansible-role-ustreamer
)
for ansible_role in "${ANSIBLE_ROLES[@]}"; do
  if [[ ! -d "roles/${ansible_role}" ]]; then
    >&2 echo "Bundle is missing Ansible role: ${ansible_role}"
    exit 1
  fi
done
