---
- name: read uStreamer settings file
  slurp:
    src: "{{ ustreamer_settings_file }}"
  register: ustreamer_settings_slurp

- name: decode settings file
  set_fact:
      ustreamer_settings: "{{ ustreamer_settings_slurp['content'] | b64decode | from_yaml }}"

- name: read ustreamer_capture_device from config file if it's not already defined
  set_fact:
    ustreamer_capture_device: "{{ ustreamer_settings['capture_device'] if ustreamer_capture_device == None and 'capture_device' in ustreamer_settings else ustreamer_capture_device }}"
  when: ustreamer_capture_device == None
