# The architecture names that yq uses differ from the names of the architecture
# that Ansible returns, so we have to translate certain names from the Ansible
# version to the yq version.
- name: define ansible to yq architecture mapping
  set_fact:
    ustreamer_yq_architecture_map:
      x86_64: amd64
      armv6l: arm
      armv7l: arm
      aarch64: arm64

- name: canonicalize yq binary architecture
  set_fact:
    ustreamer_yq_architecture: "{{ ustreamer_yq_architecture_map[ansible_architecture] | default(ansible_architecture) }}"

- name: install yq
  get_url:
    url: "https://github.com/mikefarah/yq/releases/download/{{ ustreamer_yq_version }}/yq_linux_{{ ustreamer_yq_architecture }}"
    dest: /usr/bin/yq
    owner: root
    group: root
    mode: "0755"
