#!/bin/bash
# Run this from the repository root to enable all git hooks for this project.

set -x
set -e
set -u

# If there's an existing symlink, remove it.
if [[ -L .git/hooks ]]
then
  rm .git/hooks
fi

# If it's a regular directory, remove all files.
if [[ -d .git/hooks ]]
then
  rm -rf .git/hooks
fi

ln -s -f ../hooks .git/hooks