#!/usr/bin/env python3

# Renders a Jinja2 template using TinyPilot settings data.

# To test:
#
#   $ TEMPLATE_FILE=$(mktemp) && \
#       echo 'KEYBOARD_PATH = {{ tinypilot_keyboard_interface }}'  \
#           >> ${TEMPLATE_FILE} && \
#       echo 'MOUSE_PATH = {{ tinypilot_mouse_interface }}' \
#           >> ${TEMPLATE_FILE} && \
#       PYTHONPATH="${PWD}/app" ./scripts/render-template < ${TEMPLATE_FILE}

# Ignore pylint complaint that this filename has a dash instead of an
# underscore.
# pylint:disable=invalid-name

import argparse
import sys

import jinja2

import update.settings


def main(_):
    settings = update.settings.load()

    print(jinja2.Environment().from_string(sys.stdin.read()).render(
        settings.as_dict()))


if __name__ == '__main__':
    parser = argparse.ArgumentParser(
        prog='TinyPilot Template Renderer',
        formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    main(parser.parse_args())
