#!/bin/bash

# The canonical way to update is through the update script below,
# but this file is here for backwards compatibility.

# Without this file, we have no way of giving users an update command
# that will work regardless of TinyPilot version.

if [[ "${EUID}" -ne 0 ]]; then
  >&2 echo 'This script requires root privileges.'
  >&2 echo 'Please re-run with sudo:'
  >&2 echo "  sudo ${0} $*"
  exit 1
fi

sudo /opt/tinypilot-privileged/scripts/update
