#!/bin/bash

# If a .git directory exists, the previous version was installed with the legacy
# installer, so wipe the install location.
if [[ -d /opt/tinypilot/.git ]]; then
  rm -rf /opt/tinypilot
fi
