#!/bin/bash

# Exit build script on first failure.
set -e

# Echo commands to stdout.
set -x

# Exit on unset variable.
set -u

# Ensure we are running as root user.
if [[ "$(whoami)" != "root" ]]; then
  echo "Script must be run as root user."
  exit 1
fi

# Set BRANCH variable, use either input argument or default.
REVISION="HEAD"
if (( $# > 0 )); then
  REVISION="$1"
fi

cd /opt/tinypilot

# Pull requested branch. We can’t execute this as the user `tinypilot` in order
# to be able to use SSH agent forwarding, which only works for the user `root`.
git fetch
git reset --hard "${REVISION}"
chown -R tinypilot:tinypilot .
# Apply changes by restarting server.
systemctl restart tinypilot
