#!/bin/bash

# Exit build script on first failure.
set -e

# Print commands to terminal (stderr).
set -x

# Exit on unset variable.
set -u

# Check and ensure we have passwordless sudo permissions. (The following command
# would exit with non-zero otherwise and make this script abort.)
sudo -n true

# Set REVISION variable, use either input argument or default.
REVISION="HEAD"
if (( $# > 0 )); then
  REVISION="$1"
fi

cd /opt/tinypilot

# Abort in case the repository is not clean.
if [[ -n "$(git status --porcelain)" ]]; then
  echo "There are uncommitted changes."
  exit 1
fi

# Pull requested branch. We can’t execute this as the user `tinypilot` in order
# to be able to use SSH agent forwarding, which only works for the user we are
# logged in as.
sudo chown -R "$(whoami)":"$(whoami)" .
git fetch --all
git reset --hard "${REVISION}"
chown -R tinypilot:tinypilot .

# Apply changes by restarting server.
systemctl restart tinypilot
