#!/bin/bash

# Exit on first failure.
set -e

# Echo commands before executing them, by default to stderr.
set -x

# Exit on unset variable.
set -u

# Location of app source files.
SOURCE_DIR="app"

# Run unit tests.
./node_modules/.bin/mocha \
  --recursive \
  "${SOURCE_DIR}/**/*.test.js"

./dev-scripts/lint-frontend
