#!/bin/bash

# Build TinyPilot Debian packages
#
# Usage:
#   build-debian-pkg [target architectures]
#
# target architecture: A comma-separated list of architectures that Docker
#   accepts for its --platform argument. If omitted, defaults to
#   "linux/arm/v7,linux/amd64".
#   See https://docs.docker.com/build/building/multi-platform/ for other target
#   platform options.
#
# Examples
#  build-debian-pkg "linux/arm/v7,linux/arm64"

# Exit build script on first failure.
set -e

# Echo commands before executing them, by default to stderr.
set -x

# Exit on unset variable.
set -u

BUILD_TARGETS="${1:-linux/arm/v7,linux/amd64}"

print_tinypilot_version() {
  # Format build hash suffix according to SemVer (`-ghhhhhhh` -> `+hhhhhhh`).
  git describe --tags --long |
  sed --expression 's/\(-g\([0-9a-f]\{7\}\)\)$/+\2/g'
}

TINYPILOT_VERSION="$(print_tinypilot_version)"
readonly TINYPILOT_VERSION

PKG_VERSION="$(date '+%Y%m%d%H%M%S')"
readonly PKG_VERSION

# Use plain Docker build progress output when we're running in CI.
DOCKER_PROGRESS='auto'
if [[ -n "${CI:-}" ]]; then
  DOCKER_PROGRESS='plain'
fi
readonly DOCKER_PROGRESS

DOCKER_BUILDKIT=1 docker buildx build \
  --file debian-pkg/Dockerfile \
  --platform "${BUILD_TARGETS}" \
  --build-arg TINYPILOT_VERSION="${TINYPILOT_VERSION}" \
  --build-arg PKG_VERSION="${PKG_VERSION}" \
  --target=artifact \
  --progress="${DOCKER_PROGRESS}" \
  --output "type=local,dest=$(pwd)/debian-pkg/releases/" \
  .
