#!/bin/bash

# Exit build script on first failure.
set -e

# Print commands to terminal (stderr).
set -x

# Exit on unset variable.
set -u

./dev-scripts/check-trailing-whitespace
./dev-scripts/check-trailing-newline
./dev-scripts/check-bash
./dev-scripts/build-python
./dev-scripts/build-javascript
./dev-scripts/check-style
