#!/bin/bash

# Exit build script on first failure.
set -e

# Echo commands to stdout.
set -x

# Exit on unset variable.
set -u

TINYPILOT_VERSION="$(git rev-parse --short HEAD)"
export readonly TINYPILOT_VERSION

PKG_VERSION="$(date '+%Y%m%d%H%M%S')"
export readonly PKG_VERSION

DOCKER_BUILDKIT=1 docker build \
  --file debian-pkg/Dockerfile \
  --build-arg TINYPILOT_VERSION \
  --build-arg PKG_VERSION \
  --target=artifact \
  --output "type=local,dest=$(pwd)/releases/" \
  .
