#!/bin/bash

# Exit on first failure.
set -e

# Echo commands before executing them, by default to stderr.
set -x

# Exit on unset variable.
set -u

# Run bats tests.
bats \
  --recursive \
  scripts/ \
  debian-pkg/ \
  dev-scripts/
