#!/bin/bash

# Exit build script on first failure.
set -e

# Echo commands to stdout.
set -x

# Exit on unset variable.
set -u

# Location of app source files.
SOURCE_DIR="app"

# Run unit tests.
./node_modules/.bin/mocha \
  --recursive \
  "${SOURCE_DIR}/**/*.test.js"
