#!/bin/bash

# Exit on first failure.
set -e

# Echo commands before executing them, by default to stderr.
set -x

# Exit on unset variable.
set -u

# Location of app source files.
SOURCE_DIR="app"

ADDITIONAL_PY_SCRIPTS=()
ADDITIONAL_PY_SCRIPTS+=("scripts/render-template")
ADDITIONAL_PY_SCRIPTS+=("scripts/update-service")

# Location of virtualenv.
VIRTUALENV_DIR=venv

./dev-scripts/check-for-init-py-files

# Delete pyc files from previous builds.
find . \
  -name "*.pyc" \
  -type f \
  -not -path "./${VIRTUALENV_DIR}/*" \
  -delete

# Run unit tests and calculate code coverage.
# Load module `app.log` to initialize our custom logger.
coverage run \
  --source "$SOURCE_DIR" \
  --omit "*_test.py" \
  --module \
    unittest discover --pattern "*_test.py" \
    app.log
coverage report

# Check that source has correct formatting.
yapf --diff --recursive ./

# Check correct sorting for imports.
isort \
  --recursive \
  --force-single-line-imports \
  --top log \
  --diff \
  --check-only \
  --skip-glob=third_party/* \
  --skip-glob=venv/*

# Run static analysis for Python bugs/cruft.
pyflakes "${SOURCE_DIR}/" "${ADDITIONAL_PY_SCRIPTS[@]}"

# Check for other style violations.
PYTHONPATH="${SOURCE_DIR}" pylint "${SOURCE_DIR}" "${ADDITIONAL_PY_SCRIPTS[@]}"
