#!/bin/bash
#
# Run static analysis on bash scripts.

# Exit on first failing command.
set -e

# Exit on unset variable.
set -u

BASH_SCRIPTS=()

while read -r line; do
  if head -n 1 "${line}" | grep --quiet "#!/bin/bash"; then
    BASH_SCRIPTS+=("${line}")
  fi
done < <(git ls-files)

readonly BASH_SCRIPTS

shellcheck \
  --external-sources \
  "${BASH_SCRIPTS[@]}"
