#!/bin/bash

# Verify that all text files end in a trailing newline.

# Exit on first failing command.
set -e
# Exit on unset variable.
set -u

readonly TEXT_FILES=$(grep \
  ".*" \
  --files-with-matches \
  --binary-files=without-match \
   --exclude="*.svg" \
   --exclude="*third-party*" \
   $(git ls-files | xargs)
)

success=0

for text_file in ${TEXT_FILES[*]}
do
  if ! [[ -s "${text_file}" && -z "$(tail -c 1 "${text_file}")" ]]; then
    printf "File must end in a trailing newline: ${text_file}\n" >&2
    success=-1
  fi
done

exit "${success}"
