#!/bin/bash
#
# Check that the TinyPilot scripts contain a guard against privilege escalation.
#
# This script enforces a pattern of ensuring that scripts which are writable by
# the `tinypilot` user don't get executed with unnecessary root privileges.
#
# In some rare cases, root privileges are necessary (e.g.,
# `scripts/install-bundle`) and so the opposite should be enforced (i.e.,
# ensure that the script is only executed with root privileges).

# Exit on first failing command.
set -e

# Exit on unset variable.
set -u

if MATCH="$(grep \
  --files-without-match \
  --fixed-strings \
  --regexp 'This script requires root privileges.' \
  --regexp "This script doesn't require root privileges." \
  scripts/*)"; then
  >&2 echo 'These files are missing a guard against privilege escalation:'
  >&2 echo "${MATCH}"
  >&2 echo 'Please add the following check (or similar) to the above scripts:'
  >&2 cat <<'EOF'
if [[ "${EUID}" == 0 ]]; then
  >&2 echo "This script doesn't require root privileges."
  >&2 echo 'Please re-run as tinypilot:'
  >&2 echo "  runuser tinypilot --command '$0'"
  exit 1
fi
EOF
  exit 1
fi
