#!/bin/bash

# Perform static analysis on all .deb files in the working directory.

# Exit on first failure.
set -e

# Echo commands before executing them, by default to stderr.
set -x

# Exit on unset variable.
set -u

while read -r file; do
  lintian \
    --check \
    --suppress-tags-from-file .lintianignore \
    --fail-on warning,error \
    --no-cfg \
    --tag-display-limit 0 \
    --verbose \
    "${file}"
done < <(ls -- *.deb)
