#!/bin/bash

# test if __init__.py file exists in directory containing .py files

# Exit build script on first failure.
set -e
# Echo commands to stdout.
set -x
# Exit on unset variable.
set -u

success=0

while read -r line; do
  if [ ! -f "$line/__init__.py" ]; then
    printf "Directory missing __init__.py file: %s\n" "${line}" >&2
    success=255
  fi
done < <(
  find . -type f -name '*.py' -not -path "./venv/*" -not -path "./.git/*" -exec dirname {} \; \
    | sort --unique
)

exit "${success}"
