#!/bin/bash
#
# Runs tests and static analysis on JavaScript files.

# Exit on first failure.
set -e

# Echo commands before executing them, by default to stderr.
set -x

# Exit on unset variable.
set -u

# Location of app source files.
SOURCE_DIR="app"

# Check for JavaScript anti-patterns.
./node_modules/.bin/eslint "./**/*.js" "./**/*.html"

# Run unit tests.
./node_modules/.bin/mocha \
  --recursive \
  "${SOURCE_DIR}/**/*.test.js"
