#!/bin/bash
#
# Run static analysis on bash scripts.

# Exit on first failing command.
set -e

# Exit on unset variable.
set -u

BASH_SCRIPTS=()

while read -r filepath; do
  if head -n 1 "${filepath}" | grep --quiet \
    --regexp '#!/bin/bash' \
    --regexp '#!/usr/bin/env bash' \
    --regexp '#!/usr/sh' \
    --regexp '#!/usr/bin/env sh' \
    ; then
      BASH_SCRIPTS+=("${filepath}")
  fi
done < <(git ls-files)

readonly BASH_SCRIPTS

shellcheck "${BASH_SCRIPTS[@]}"
