#!/bin/bash

# Check for trailing whitespace

# Exit on first failing command.
set -e
# Exit on unset variable.
set -u

if grep \
  "\s$" \
  --line-number \
  --binary-files=without-match \
  --exclude="*third-party*" \
  $(git ls-files | xargs); then
  echo "ERROR: Found trailing whitespace";
  exit 1;
fi
