#!/bin/bash
#
# Run static analysis on bash scripts.

# Exit on first failing command.
set -e

# Exit on unset variable.
set -u

BASH_SCRIPTS=()

while read -r line; do
  BASH_SCRIPTS+=("${line}")
done < <(find . \
  -not -path './\.*' \
  -not -path './venv/*' \
  -not -path './node_modules/*' \
  -type f \
  -exec bash -c 'head -n 1 $1 | grep --quiet "#!/bin/bash"' _ {} \; \
  -print)

shellcheck "${BASH_SCRIPTS[@]}"
