#!/bin/bash

# Verify that all text files end in a trailing newline.

# Exit on first failing command.
set -e
# Exit on unset variable.
set -u

readonly FILES=$(find . \
  -type f \
  -not -path "./.git/*" \
  -not -path "./venv/*" \
  -not -path "./node_modules/*" \
  -not -path "*/third_party/*" \
  -not -path "*/third-party/*" \
  -not -path "*.svg" \
  -exec grep \
  --binary-files=without-match \
  --quiet \
  . {} \; -print)

success=0

for source_file in ${FILES[*]}
do
  if ! [[ -s "${source_file}" && -z "$(tail -c 1 "${source_file}")" ]]; then
    printf "File must end in a trailing newline: ${source_file}\n" >&2
    success=-1
  fi
done

exit "${success}"
