#!/bin/bash

# test if __init__.py file exists in directory containing .py files
CHECK_INIT_FILE_EXISTS=$(find . -type f -name '*.py' -not -path "./venv/*" -exec dirname {} \; | sort | uniq | xargs -I % bash -c """
  f=%/__init__.py
  if [ ! -f \$f ]; then
    echo ' - '%
  fi
""")

if [ -n "$CHECK_INIT_FILE_EXISTS" ]; then
  HELP_TEXT="Directories missing __init__ file"
  printf "\n%s\n%s\n" "$HELP_TEXT" "$CHECK_INIT_FILE_EXISTS"
  exit 1
fi
