#!/bin/bash
#
# Runs Static Application Security Testing (SAST) on files.

# Exit on first failure.
set -e

# Echo commands before executing them, by default to stderr.
set -x

# Exit on unset variable.
set -u

semgrep scan --error --text
