#!/bin/bash
#
# Runs tests and static analysis on Python files.

# Exit on first failure.
set -e

# Echo commands before executing them, by default to stderr.
set -x

# Exit on unset variable.
set -u

# Delete pyc files from previous builds.
find . \
  -name '*.pyc' \
  -type f \
  -not -path './venv/*' \
  -delete

# Run unit tests and calculate code coverage.
# Load module `app.log` to initialize our custom logger.
coverage run \
  --source app/ \
  --omit '*_test.py' \
  --module \
    unittest discover --pattern '*_test.py' \
    app.log
coverage report

# Check for Python init files.
INIT_FILES_OK=true
while read -r directory; do
  if [[ ! -f "${directory}/__init__.py" ]]; then
    printf "Directory missing __init__.py file: %s\n" "${directory}" >&2
    INIT_FILES_OK=false
  fi
done < <(
  find . \
    -type f \
    -name '*.py' \
    -not -path './venv/*' \
    -not -path './.git/*' \
    -exec dirname {} \; \
    | sort --unique
)
"${INIT_FILES_OK}" || exit 1

# Check that source has correct formatting.
yapf --diff --recursive ./

# Gather names of all Python scripts in the scripts/ folder.
PYTHON_SCRIPTS=()
mapfile -t PYTHON_SCRIPTS < <(grep -rl '^#!.*python' scripts/)
readonly PYTHON_SCRIPTS

# Run static analysis for Python bugs/cruft.
ruff check \
  app/ \
  "${PYTHON_SCRIPTS[@]}"

# Check for other style violations.
PYTHONPATH='app/' \
  pylint \
  app/ \
  "${PYTHON_SCRIPTS[@]}"
