#!/bin/bash

# Checks formatting for non-Python files.

# Exit on first failure.
set -e

# Echo commands before executing them, by default to stderr.
set -x

# Exit on unset variable.
set -u

# Change directory to repository root.
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
readonly SCRIPT_DIR
cd "${SCRIPT_DIR}/.."

# Check code style with the Prettier libary.
if ! ./node_modules/.bin/prettier --check . ; then
  echo "Try running ./dev-scripts/fix-style to fix formatting" >&2
  exit 1
fi
