#!/bin/bash

# Exit build script on first failure.
set -e

# Exit on unset variable.
set -u

if ! ./node_modules/.bin/prettier --check app ; then
  echo "Try running ./dev-scripts/fix-frontend-format to fix formatting" >&2
  exit 1
fi
