#!/bin/bash

# Decode the EDID from the TinyPilot install defaults.

# This script facilitates debugging the EDID and creates helpful logs of EDID
# changes in CI.

# Exit build script on first failure.
set -e

# Echo commands before executing them, by default to stderr.
set -x

# Exit on unset variable.
set -u

# Change directory to repository root.
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
readonly SCRIPT_DIR
cd "${SCRIPT_DIR}/.."

PYTHONPATH=./app \
  ./scripts/render-template \
  <<< '{{ ustreamer_edid }}' | \
  edid-decode --check
