#!/bin/bash

# Decode the EDID from the ansible-role-ustreamer defaults.

# This script facilitates debugging the EDID and creates helpful logs of EDID
# changes in CI.

# Exit build script on first failure.
set -e

# Echo commands before executing them, by default to stderr.
set -x

# Exit on unset variable.
set -u

# Extract the EDID from the inline YAML definition.
grep "ustreamer_edid:" -A16 ansible-role-ustreamer/defaults/main.yml | \
  `# Strip the line with ustreamer_edid` \
  tail --lines=+2 | \
  `# Strip whitespace` \
  tr --delete "[:blank:]" | \
  edid-decode --check
