#!/bin/bash

# Exit on unset variable.
set -u

LOG_FILE=$(mktemp)
echo "Writing diagnostic logs to $LOG_FILE"

echo "Checking TinyPilot version..."
cd /opt/tinypilot
printf "TinyPilot version: %s\n" $(git rev-parse HEAD) >> "$LOG_FILE"

echo "Checking uStreamer version..."
cd /opt/ustreamer
printf "uStreamer version: %s\n" $(git rev-parse HEAD) >> "$LOG_FILE"

echo "Checking TinyPilot logs..."
printf "TinyPilot logs\n\n" >> "$LOG_FILE"
sudo journalctl -u tinypilot | tail -n 80 >> "$LOG_FILE"
printf "\n" >> "$LOG_FILE"

echo "Checking uStreamer logs..."
echo "uStreamer logs" >> "$LOG_FILE"
sudo journalctl -u ustreamer | tail -n 80 >> "$LOG_FILE"
printf "\n" >> "$LOG_FILE"

echo "Checking nginx logs..."
echo "nginx logs" >> "$LOG_FILE"
sudo journalctl -u nginx >> "$LOG_FILE"
sudo tail -n 100 /var/log/nginx/error.log >> "$LOG_FILE"

printf "Your log:\n\n"
cat "$LOG_FILE"
printf "-------------------------------------\n"

echo -n "Upload your log file? You can review it above to see what information it contains (y/n)? "
read answer
if [ "$answer" != "${answer#[Yy]}" ] ;then
    URL=$(cat "$LOG_FILE" | curl -F 'sprunge=<-' http://sprunge.us)
    printf "Copy the following URL into your bug report:\n\n\t"
    printf "${URL}\n"
else
    echo "Log file not uploaded."
    echo "If you decide to share it, run:"
    echo 'cat "$LOG_FILE" | curl -F \'sprunge=<-\' http://sprunge.us)'
fi
