#!/bin/bash
#
# Enable passwordless sudo for paths that TinyPilot requires.

# Note: If you run with passwordless sudo enabled globally for your user
# account, you don't need to run this script.

# In production, TinyPilot has permission to run an allowlist of paths with sudo
# permissions. For developers who don't have passwordless sudo enabled globally
# for their user account, certain TinyPilot functionality will fail waiting on a
# sudo escalation prompt. This script prevents those failures by granting your
# dev user account passwordless sudo for the specific paths the TinyPilot dev
# server needs.
#
# To undo this script's changes, run:
#   sudo rm /etc/sudoers.d/tinypilot

if [[ "${EUID}" -ne 0 ]]; then
  echo "This script requires root privileges." >&2
  echo "Please re-run with sudo:" >&2
  echo "  sudo ${0}" >&2
  exit 1
fi

# Exit build script on first failure.
set -e

# Echo commands before executing them, by default to stderr.
set -x

# Exit on unset variable.
set -u

# This script must be run as sudo but needs the name of the user who invoked it.
readonly USERNAME="${SUDO_USER}"

# Change directory to repository root.
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
readonly SCRIPT_DIR
cd "${SCRIPT_DIR}/.."

readonly SUDOERS_SOURCE="./debian-pkg/etc/sudoers.d/tinypilot"
readonly SUDOERS_DEST='/etc/sudoers.d/tinypilot'

# Create parent folder in case it does not exist.
sudo mkdir -p "$( dirname ${SUDOERS_DEST} )"

# Copy the sudoers file from the debian package while modifying it to apply to
# the invoking user.
sed "s/^tinypilot/${USERNAME}/" < "${SUDOERS_SOURCE}" > "${SUDOERS_DEST}"

echo "Wrote TinyPilot dev sudoers.d file to \"${SUDOERS_DEST}\""
