#!/bin/bash

# Configure Docker to support multiarch builds, allowing it to use QEMU to build
# images targeting different CPU architectures.

# Exit script on first failure.
set -e

# Echo commands before executing them, by default to stderr.
set -x

# Exit on unset variable.
set -u

# Enable multiarch builds with QEMU.
docker run \
  --rm \
  --privileged \
  multiarch/qemu-user-static \
  --reset \
  -p yes

# Create multiarch build context.
docker context create builder

# Create multiplatform builder.
docker buildx create builder \
  --name builder \
  --driver docker-container \
  --use

# Ensure builder has booted.
docker buildx inspect --bootstrap
