#!/bin/bash

# Checks for JavaScript anti-patterns.

# Exit on first failure.
set -e

# Echo commands before executing them, by default to stderr.
set -x

# Exit on unset variable.
set -u

npm run lint
