#!/bin/bash

# Checks for SQL script anti-patterns.

# Exit build script on first failure.
set -e

# Print commands to terminal (stderr).
set -x

# Exit on unset variable.
set -u

# Change directory to repository root.
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
readonly SCRIPT_DIR
cd "${SCRIPT_DIR}/.."

sqlfluff lint \
  --disable_progress_bar \
  --dialect sqlite \
  app/db/migrations
