#!/bin/bash

# Exit build script on first failure.
set -e

# Echo commands to stdout.
set -x

# Exit on unset variable.
set -u

# Serve TinyPilot in dev mode.
HOST=0.0.0.0 \
  PORT=8000 \
  DEBUG=1 \
  USE_RELOADER=1 \
  APP_SETTINGS_FILE=../dev_app_settings.cfg \
  ./app/main.py
