#!/bin/bash

# Exit build script on first failure.
set -e

# Echo commands to stdout.
set -x

# Exit on unset variable.
set -u

# Watch frontend sources and re-run bundler automatically.
./node_modules/.bin/rollup --config --watch
